name: Run Tests
on: [push, pull_request]

env:
  DEBIAN_FRONTEND: noninteractive
  RUST_BACKTRACE: 1
  TZ: Europe/Berlin

jobs:
  buildAndTest:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies for Linux
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y curl build-essential cmake pkg-config cargo libgtk-3-dev

      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable

      - uses: clechasseur/rs-cargo@v3
        if: ${{ github.ref_name != 'main' }}
        with:
          command: test

      - uses: clechasseur/rs-cargo@v3
        if: ${{ github.ref_name == 'main' }}
        with:
          command: test
          args: --release

      - uses: clechasseur/rs-cargo@v3
        with:
          command: clippy
